### ISSUE TITLE
Text display of station names

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/result_manager#10]
Each of the stations is represented as a longitude and latitude point that we can view.  Each of these points has a name that's contained in the sta data frame.  We'd like to display these values on the main plot. There are two options that we've considered for this:

1. Show all station names on the screen at once. This is nice in the sense that it conveys a lot of information but it could be too overwhelming to look at with hundreds of numbers on the screen at once.

2. Create a "hover" property for each station. When hovering over a station, display a small popup/tooltip/hover that shows the station name. See "Mouse over dots" example at: https://docs.bokeh.org/en/2.4.3/docs/user_guide/tools.html

It's worth exploring to see which works best.

**Comment by maxballison** [comment]
Just added a hover tool to the 'hover_stations' branch. When you turn on the 'loc' checkbox to see all of the stations, you have the ability now to hover over the stations to see their names.

This is a very nice feature and seems to be better than just showing all station names. After some testing, it seemed like having all names show up at once was too busy. There might also be another way, though, to show all names within a certain radius of the mouse, but I like the current hover feature.

One slight problem is that the station dots are pretty small, so hovering over them as of now takes a bit of precision. I think we can maybe just slightly increase their size, though.
