### ISSUE TITLE
Decide on colors for each velocity field

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/result_manager#2]
Assigning to @jploveless because he has experience with what worked well and what didn't in ResultManager.

##### run_1
- `obs_vel_1`: ???
- `mod_vel_1`: ???
- `res_vel_1`: ???
- `rot_vel_1`: ???
- `seg_vel_1`: ???
- `tri_vel_1`: ???
- `str_vel_1`: ???
- `mog_vel_1`: ???

##### run_2
- `obs_vel_2`: ???
- `mod_vel_2`: ???
- `res_vel_2`: ???
- `rot_vel_2`: ???
- `seg_vel_2`: ???
- `tri_vel_2`: ???
- `str_vel_2`: ???
- `mog_vel_2`: ???

**Comment by jploveless** [comment]
In `result_manager`, we could use 

`from bokeh.colors import RGB`

and use the same colors as ResultManager, which are:

* obs_vel_1: `color = RGB(r = 0, g = 0, b = 256)`
* mod_vel_1: `color = RGB(r = 256, g = 0, b = 0)`
* res_vel_1:  `color = RGB(r = 256, g = 0, b = 256)`'
* rot_vel_1:  `color = RGB(r = 0, g = 256, b = 0)`
* seg_vel_1:  `color = RGB(r = 0, g = 256 b = 256)`
* tri_vel_1:  `color = RGB(r = 256, g = 166, b = 0)`
* str_vel_1:  `color = RGB(r = 0, g = 128, b = 128)`
* mog_vel_1: N/A

For * run_2*, all color triplets are multiplied by 0.8, and the colored arrows are actually overlain on gray arrows of width 2, of grayscale value  `color = RGB(r = 205, g = 205, b = 205)`. This gives a sort of highlighted appearance, but the downside is that it doubles the number of plotted line objects.

**Comment by brendanjmeade** [comment]
Understood and I'll work on that!

**Comment by jploveless** [comment]
Half addressed in https://github.com/brendanjmeade/result_manager/commit/1aaacf4850e7fcfaeaf937eae1fef27bd003d505

Still need to set a unique color for Mogi and then add folder 2 with modified colors.

**Comment by jploveless** [comment]
Unique colors implemented in https://github.com/brendanjmeade/result_manager/commit/6773bbcf72a7923e05521ea3a94f518353de5151

I didn't add the gray highlighting, but I think the colors are sufficiently distinct as is.
