### ISSUE TITLE
Add initial draw and scaling for all folder one velocity fields

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/result_manager#3]

**Comment by jploveless** [comment]
Scaling both folders' fields is trickier than I thought. I created a new branch https://github.com/brendanjmeade/result_manager/commit/55acb603b2c719e70dc5fe596a833111aa25511d that adds a bunch of copied variables in the slider JS, but it's not working, and it's throwing JS console errors that suggest that source1 and source2 are getting convolved or improperly parsed. I left `main` with the standard callback that doesn't attempt to scale folder 2 vectors; it still works fine for all fields of folder 1.
